learningAttendance/urls.py
from django.urls import path
from . import views
from registration.views import UnitRegisteredStudents, UnitRegistrationView

app_name = 'meru_learning'
urlpatterns = [

    path('students_list/', views.StudentListView.as_view(), name="students_list"),

    # urls for school
    path('', views.schools_list_view, name="schools_list"),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name="school_detail"),
    path('new/', views.SchoolCreateView.as_view(), name='school_create'),
    path('<int:pk>/edit/', views.SchoolUpdateView.as_view(), name='school_update'),
    path('<int:pk>/delete/', views.SchoolDeleteView.as_view(), name='school_delete'),

    # urls for course
    path('<slug:slug>/new/', views.CourseCreateView.as_view(), name='course_create'),
    path('<slug:slug>/', views.CoursesListView.as_view(), name='courses_list'),
    
    path('<slug:slug>/<int:pk>/', views.CourseDetailView.as_view(), name="course_detail"),
    path('<slug:slug>/<int:pk>/edit/', views.CourseUpdateView.as_view(), name='course_update'),
    path('<slug:slug>/<int:pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),

    # urls for units
    path('<str:school>/<slug:slug>/',
         views.UnitsListView.as_view(), name='units_list'
         ),
    path('<str:school>/<slug:slug>/students/',
         views.StudentListView.as_view(), name='students'
         ),
    path('<str:school>/<slug:slug>/new/', views.UnitCreateView.as_view(), name='unit_create'),
    path('<str:school>/<slug:slug>/<int:pk>/', views.UnitDetailView.as_view(), name="unit_detail"),
    path('<str:school>/<slug:slug>/<int:pk>/edit/', views.UnitUpdateView.as_view(), name='unit_update'),
    path('<str:school>/<slug:slug>/<int:pk>/delete/', views.UnitDeleteView.as_view(), name='unit_delete'),


     #urls for lectures
    path('<str:school>/<str:course>/<slug:slug>/',
         views.LecturesListView.as_view(), name='lectures_list'
    ),
    path('<str:school>/<str:course>/<slug:slug>/new/', views.LectureCreateView.as_view(), name='lecture_create'),
     path('<str:school>/<str:course>/<str:unit>/<slug:slug>/',
         views.LectureDetailView.as_view(), name='lectures_detail'
         ),
    path('<str:school>/<str:course>/<slug:slug>/<int:pk>/edit/', views.LectureUpdateView.as_view(), name='lecture_update'),
    path('<str:school>/<str:course>/<slug:slug>/<int:pk>/delete/', views.LectureDeleteView.as_view(), name='lecture_delete'),
    


    path('<str:school>/<str:course>/<str:unit>/<slug:slug>/attendance/',
         views.AttendanceListView.as_view(), name='attendance_list'
         ),
    path('<str:school>/<str:course>/<slug:slug>/students',
         UnitRegisteredStudents.as_view(), name='unit_student_list'
         ),
    path('<str:school>/<str:course>/<slug:slug>/students/new',
         UnitRegistrationView.as_view(), name='unit_student_registration'
         ),
   

]

meru_class_attendance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('learning/', include('learningAttendance.urls')),
    path('registration/', include('registration.urls')),
    # path('attendance/', include('attendance.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from learningAttendance.views import StudentListView


urlpatterns = [
    path('', views.login_request, name='login_request'),
    path('student_login/', views.student_login, name='student_login'),
    path('staff_login/', views.staff_login, name='staff_login'),
    path('logout/', views.user_logout, name='logout'),


    path('profile/', views.my_course_info, name="profile"),
    path('profile>/<slug:slug>/units',
         views.StudentUnitsList.as_view(), name='all_units'
         ),
    path("profile/registered_units/", views.registered_units_view, name="registered_units"),
    path('profile/registered_units/<slug:slug>/attendance/',
         views.student_attendance_report, name='student_attendance_report'
         ),
    path('profile/registered_units/<slug:slug>/',
         views.StudentLecturesList.as_view(), name='student_lectures'
         ),

    path('update_profile_pic', views.update_profile_pic, name="update_profile_pic"),



    path('lecturer/', views.lecturer_profile, name="lecturer_profile"),
    path('profile_update', views.update_lecturer_pic, name="update_lecturer_pic"),
    path('lecturer/units/', views.lecturer_units, name="lecturer_units"),
    path('lecturer/units/<slug:slug>/',
         views.LecturesListView.as_view(), name='lecturer_lectures'
         ),
    path('lecturer/units/<slug:slug>/attendance',
         views.LecturesAttendanceView.as_view(), name='lecturer_attendance'
         ),  
     path('lecturer/units_attendance/', views.lecturer_units_report, name="lecturer_units_report"),
     path('lecturer/<slug:slug>/units_attendance/', views.lecturer_lectures_report, name="lecturer_lectures_report"),
     path('lecturer/units/<slug:slug>/attendance_report',
         views.lecturer_student_attendance_report, name='lecture_attendance_report'
         ),
    path('lecturer/units/<str:unit>/<slug:slug>/',
         views.LectureDetailView.as_view(), name='lecture_detail'
         ),



    path('students/', views.UserListView.as_view(), name="users_list"),

    path('students/new/', views.UserCreateView.as_view(), name='user_new'),
    path('students/<slug:slug>/', views.UserDetailView.as_view(), name="user_detail"),
    path('students/<slug:slug>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('students/<slug:slug>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
     path('students/units/<str:unit>/<slug:slug>/lectures/',
         views.StudentLectureDetailView.as_view(), name='student_lecture_detail'
         ),

]

learningAttendance/models.py
from tabnanny import verbose
from django.db import models
from django.template.defaultfilters import slugify
import os
# from users.models import CustomUser
from django.urls import reverse
from django.conf import settings

semesters = (
    (1, 1),
    (2, 2),
    (3, 3),
)
academic_years = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),

)


def save_school_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    filename = 'School_Pictures/{}.{}'.format(instance.name, ext)
    return os.path.join(upload_to, filename)


class School(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(upload_to=save_school_image, blank=True, verbose_name='school image')
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('meru_learning:school_detail', args=[str(self.pk)])


def save_course_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    filename = 'course_pictures/{}.{}'.format(instance.course_name, ext)
    return os.path.join(upload_to, filename)


class Course(models.Model):
    course_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='courses')
    image = models.ImageField(upload_to=save_course_image, blank=True, verbose_name='course image')
    description = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.course_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.course_name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('meru_learning:courses_list', args=[slugify(self.school.slug)])

def course_unit_pdf(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.course:
        filename = 'course_pdf/{}/{}.{}'.format(instance.course, instance.course, ext)
        if os.path.exists(filename):
            new_name = str(instance.course) + str('1')
            filename = 'course_pdf/{}/{}.{}'.format(instance.course, new_name, ext)
    return os.path.join(upload_to, filename)

class CourseUnits(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='courses')
    unit_pdf = models.FileField(upload_to=course_unit_pdf, verbose_name='Unit PDF', blank=True)


def save_unit_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.unit_name:
        filename = 'Unit_Pictures/{}.{}'.format(instance.unit_name, ext)
    return os.path.join(upload_to, filename)


class Unit(models.Model):
    unit_name = models.CharField(max_length=100, unique=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='units')
    slug = models.SlugField(null=True, blank=True)
    year = models.IntegerField(choices=academic_years, default=1)
    semester = models.IntegerField(choices=semesters, default=1)
    image = models.ImageField(upload_to=save_unit_image, blank=True, verbose_name='unit image')
    is_offered = models.BooleanField(default=False)
    description = models.TextField(max_length=500, blank=True)
    lecturer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Lecture", default=1)

    def __str__(self):
        return self.unit_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.unit_name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {
            'slug':self.course.slug,
            'school':self.course.school.slug,
        }
        return reverse('meru_learning:units_list', kwargs=kwargs)


def save_lecture_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.lecture_name:
        filename = 'lecture_files/{}/{}.{}'.format(instance.lecture_name, instance.lecture_name, ext)
        if os.path.exists(filename):
            new_name = str(instance.lecture_name) + str('1')
            filename = 'Lecture_images/{}/{}.{}'.format(instance.lecture_name, new_name, ext)
    return os.path.join(upload_to, filename)


class Lecture(models.Model):
    lecture_name = models.CharField(max_length=100, unique=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="Lecturer")
    created_at = models.DateTimeField(auto_now_add=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='lectures')
    position = models.PositiveSmallIntegerField(verbose_name='Chapter no.')
    slug = models.SlugField(null=True, blank=True)
    # position represents chaters...1 is chapter one and so on
    video = models.FileField(upload_to=save_lecture_files, verbose_name='video', blank=True)
    ppt = models.FileField(upload_to=save_lecture_files, verbose_name='presentation', blank=True, null=True)
    notes = models.FileField(upload_to=save_lecture_files, verbose_name='notes', blank=True, null=True)
    
    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.lecture_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.lecture_name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug,
            'unit':self.unit.slug,
            'course':self.unit.course.slug,
            'school':self.unit.course.school.slug,
        }
        return reverse('meru_learning:lectures_detail', kwargs=kwargs)

learningAttendance/views.py
from http.client import HTTPResponse
from multiprocessing import context
from tkinter import E
from django.shortcuts import render, redirect
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404
from .models import School, Unit, Course, Lecture, CourseUnits
from django.views.generic import (DetailView, CreateView, UpdateView, DeleteView)


# Views fo schools (Faculty)
# 1 list
def schools_list_view(request):
    if request.user.is_superuser:
        schools = School.objects.all()
    elif request.user.is_staff:
        schools = None
    else:
        schools = School.objects.filter(name=request.user.school)
    return render(request, "school/school_list_view.html", {"schools": schools})


# 2 detail
class SchoolDetailView(DetailView):
    model = School
    template_name = 'school/school_detail.html'


# 3 new school
class SchoolCreateView(CreateView):
    model = School
    template_name = 'school/school_create.html'
    fields = ['name', 'image', 'description',
              ]


# 4 update existing school
class SchoolUpdateView(UpdateView):
    model = School
    template_name = 'school/school_update.html'
    fields = ['name', 'image', 'description', ]


# 5 delete
class SchoolDeleteView(DeleteView):
    model = School
    template_name = 'school/school_delete.html'
    success_url = reverse_lazy('meru_learning:schools_list')


# Views fo courses
# 1 list
class CoursesListView(DetailView):
    model = School
    context_object_name = 'schools'
    template_name = "course/courses_list_view.html"


# 2 detail
class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/course_detail.html'


# 3 new course
class CourseCreateView(CreateView):
    model = Course
    template_name = 'course/course_create.html'
    fields = ['course_name', 'school', 'image', 'description', ]


# 4 update existing course
class CourseUpdateView(UpdateView):
    model = Course
    template_name = 'course/course_update.html'
    fields = ['course_name', 'school', 'image', 'description', ]


# 5 Delete course
class CourseDeleteView(DeleteView):
    model = Course
    template_name = 'course/course_delete.html'
    success_url = reverse_lazy('meru_learning:schools_list')


# 6 students registered
class StudentListView(DetailView):
    context_object_name = 'courses'
    model = Course
    template_name = "course/students.html"


# Views fo Units
# 1 list
class UnitsListView(DetailView):
    context_object_name = 'courses'
    model = Course
    template_name = "unit/units_list_view.html"


def unit_list_pdf(request, pk):
    units_list =[]
    course = get_object_or_404(Course, pk=pk)
    units = Unit.objects.filter(course=course)
    with open(f'units_pdf/{course.course_name}.csv', 'w+') as f:
        for unit in units:
            units_list.append(unit)
            print(unit)
        for unit_to_add in units_list:
            unit_list = f.readlines()
            unit_names = []
            for line in unit_list:
                entry = line.split(",")
                unit_names.append(entry[0])
            unit = unit_to_add
            if unit not in unit_names:
                f.writelines(f'\n{unit.unit_name}, {unit.course}, {unit.is_offered}, {unit.semester},{unit.lecturer.first_name} {unit.lecturer.last_name}')
                load_files =CourseUnits.objects.create(
                    course=course,
                    unit_pdf=f,
                )
                load_files.save()
    context= {
        "pdf":f,
    }
    return render(request, "course/course_units_pdf.html", context)
          
   


# 2 detail
class UnitDetailView(DetailView):
    model = Unit
    template_name = 'unit/unit_detail.html'


# 3 new unit
# def unit_create_view(request, slug):

class UnitCreateView(CreateView):
    model = Unit
    template_name = 'unit/unit_create.html'
    fields = ['unit_name', 'course', 'year', 'semester', 'image', 'is_offered', 'description', 'lecturer']


# 4 update existing unit
class UnitUpdateView(UpdateView):
    model = Unit
    template_name = 'unit/unit_update.html'
    fields = ['unit_name', 'course', 'year', 'semester', 'image', 'is_offered', 'description', 'lecturer']


# 5 Delete unit
class UnitDeleteView(DeleteView):
    model = Unit
    template_name = 'unit/unit_delete.html'
    success_url = reverse_lazy('meru_learning:schools_list')

#views for lecture
#list
class LecturesListView(DetailView):
    context_object_name = 'units'
    model = Unit
    template_name = "lecture/lectures_list_view.html"

# 2 detail
class LectureDetailView(DetailView):
    context_object_name = 'lecture'
    model = Lecture
    template_name = "lecture/lecture_detail_view.html"


# 3 new unit
class LectureCreateView(CreateView):
    model = Lecture
    template_name = 'lecture/lecture_create.html'
    fields = ['lecture_name', 'created_by','position', 'unit', 'video', 'ppt', 'notes']


# 4 update existing lecture
class LectureUpdateView(UpdateView):
    model = Lecture
    template_name = 'lecture/lecture_update.html'
    fields = ['lecture_name', 'created_by','position', 'unit', 'video', 'ppt', 'notes']


# 5 Delete lecture
class LectureDeleteView(DeleteView):
    model = Lecture
    template_name = 'lecture/lecture_delete.html'
    success_url = reverse_lazy('meru_learning:schools_list')





class AttendanceListView(DetailView):
    context_object_name = 'lectures'
    model = Lecture
    template_name = "attendance_list.html"

learningAttendance/templates/course/course_create.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container-fluid">
    <div style="padding: 30px;">
        <p></p>
    </div><h1 class="text-white display-2">New Course</h1>
    <form action="" method="POST" enctype="multipart/form-data" style="color: rgb(223, 178, 152); font-size:large; font-weight:bold; background-color:black">
        {% csrf_token %}
        {{form|crispy}}<br>
         <h1 class=""><input class="btn btn-white display-2" type="submit" value="Add" /></h1>
        <a href="{% url 'meru_learning:schools_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
        </div>
        <div style="padding: 30px;">
            <p></p>
        </div>
</div>

{% endblock content %}

learningAttendance/templates/course/course_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div style="padding: 40px;">
        <p></p>
    </div>
   <h1 class="text-white display_1">Delete Course</h1><br>
    <form action="" method="post">{% csrf_token %}
        <div class="alert alert-danger text-center " role="alert">
            <h1>Are you sure you want to delete this Course ?</h1>
            <h2 class="text-white">Course : {{course.course_name}}</h2><br>
            

        <hr>
        <h2>
            <input class="bg-danger" type="submit" value="Confirm" />
        </h2>
             </div>
    </form>
    <div style="padding: 30px;">
        <p></p>
    </div>
</div>
{% endblock content %}

learningAttendance/templates/course/course_detail.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
    <div style="padding: 30px;">
        <p></p>
    </div>
        <div class="row justify-content-center align-items-center">
            <div class="col-12 col-md-5 image-wrapper">
                {% if course.image %}
                <img src="{{ course.image.url }}" alt="Course Iamge">
                {%else%}
                <img src="" alt="Course Image">
                {% endif%}
            </div>
            <div class="col-12 col-md">
                <div class="text-wrapper">
                    <h1 class="mbr-section-title mbr-fonts-style mb-3 display-3">
                        <strong>{{course.course_name}}</strong></h1>
                    <p class="mbr-text mbr-fonts-style display-7 text-white">
                        {{course.description}}</p>
                    <div class="mbr-section-btn mt-3"><a class="btn btn-black display-4" href="{% url 'meru_learning:course_update' slug=course.slug pk=course.pk %}">Update</a>
                        <a class="btn btn-black display-4" href="{% url 'meru_learning:units_list' slug=course.slug  school=course.school%}">View Units&nbsp;</a>
                        <a class="btn btn-secondary display-4" href="{% url 'meru_learning:course_delete' slug=course.slug pk=course.pk %}">Delete&nbsp;</a></div>
                </div>
            </div>
        </div>
        <div style="padding: 30px;">
            <p></p>
        </div>
    </div>


{% endblock %}

learningAttendance/templates/course/course_units_pdf.html
{% extends 'base.html' %}

{% block content %}
 <div class="container-fluid">
    <div style="padding: 30px;">
        <p></p>
        <h1>Download Units List</h1>
    </div>
       
                      
                        <a class="btn btn-secondary display-4" href="" class="btn btn-black" >
                            <h2>
                                <span>Download Unit List</span>
                                <span>{{pdf}}</span>
                             </h2>
                      </a>
                </div>
            </div>
        </div>
        <div style="padding: 30px;">
            <p></p>
        </div>
    </div>


{% endblock %}

learningAttendance/templates/course/course_update.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container-fluid">
    <div style="padding: 30px;">
        <p></p>
    </div>
    <form action="" method="POST" enctype="multipart/form-data" style="color: rgb(223, 178, 152); font-size:large; font-weight:bold; background-color:black">
        {% csrf_token %}
        {{form|crispy}}<br>
         <h1 class=""><input class="btn btn-white display-2" type="submit" value="Update" /></h1>
        <a href="{% url 'meru_learning:school_detail' pk=course.school.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
        </div>
        <div style="padding: 30px;">
            <p></p>
        </div>
</div>

{% endblock content %}

learningAttendance/templates/course/courses_list_view.html
{% extends 'base.html' %}

{% block content %}
{% load static %}


<section data-bs-version="5.1" class="features4 cid-tmkn3Rbx6V" id="features4-2">
    
  <div class="mbr-overlay"></div>
  <div class="container">
    <div class="">
      <a href="{% url 'meru_learning:course_create' slug=schools.slug %}" class="btn btn-success" style="background-color:#00bcd4;">
      <h2>
          <span>+ New Course</span>
      </h2>
  </a>
  </div>
      <div class="mbr-section-head">
          <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-1">
              <strong>Courses </strong></h4>
      </div>
      <div class="row mt-4">{% for course in schools.courses.all %}
          <div class="item features-image сol-12 col-md-6 col-lg-4">
              
              <div class="item-wrapper">
                  <div class="item-img">
                    {% if course.image %}
                      <img src="{{course.image.url}}" alt="Course Pic" title="">
                    {%endif%}
                  </div>
                  <div class="item-content">
                      <h5 class="item-title mbr-fonts-style display-7"><strong>{{course.course_name}}</strong></h5>
                      <p class="item-title mbr-fonts-style display-7"><strong>{{course.description|truncatechars:75}}</strong></p>
                  </div>
                  <div class="mbr-section-btn item-footer mt-2">
                    <a href="{% url 'meru_learning:units_list' slug=course.slug school=schools.slug %}" class="btn item-btn btn-black display-7" target="">View Units</a>
                     
                    <a href="{% url 'meru_learning:students' slug=course.slug school=schools.slug %}" class="btn item-btn btn-black display-7" target="">Registered Students
                    </a> 
                    <a href="{% url 'meru_learning:course_detail' pk=course.pk slug=course.slug  %}" class="btn item-btn btn-secondary display-7" target="">See more >></a>
                  </div>
              </div>
              
          </div>
          {% endfor%}
      </div>
  </div>
</section>

{% endblock %}

learningAttendance/templates/course/students.html
{% extends 'base.html'%}

{%block content%}
<div class="container-fluid">
  <div style="padding: 30px;">
    <div class="row">
      <div class="col-12">
        <div class="card bg-light ms-6 me-6 mb-6 display-2">
          <div class="card-header">
           Registered students
          </div>
          <div class="card-body">
            <p class="card-text">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Student Name</th>
                      <th scope="col">Reg Number</th>
                      <th scope="col">Course</th>
                      <th scope="col">year</th>
                      <th scope="col">semester</th>
                      <th scope="col">School</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for user in courses.users.all %}
                       <tr>
                          <td>{{user.first_name}} {{user.last_name}}</td>
                          <td>{{user.username}}</td>
                          <td>{{user.course}}</td>
                          <td>{{user.year}}</td>
                          <td>{{user.semester}}</td>
                          <td>{{user.school}}</td>
                       </tr>
                   {% endfor %}
                  </tbody>
                </table>
              </div>
            </p>
          </div>
      </div>
      
       
      </div>
      </div>
      <div style="padding: 80px;">
          <p>



          </p>
      </div>
</div>


{%endblock%}