learningAttendance/urls.py
from django.urls import path
from . import views
from registration.views import UnitRegisteredStudents, UnitRegistrationView

app_name = 'meru_learning'
urlpatterns = [

    path('students_list/', views.StudentListView.as_view(), name="students_list"),

    # urls for school
    path('', views.schools_list_view, name="schools_list"),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name="school_detail"),
    path('new/', views.SchoolCreateView.as_view(), name='school_create'),
    path('<int:pk>/edit/', views.SchoolUpdateView.as_view(), name='school_update'),
    path('<int:pk>/delete/', views.SchoolDeleteView.as_view(), name='school_delete'),

    # urls for course
    path('<slug:slug>/new/', views.CourseCreateView.as_view(), name='course_create'),
    path('<slug:slug>/', views.CoursesListView.as_view(), name='courses_list'),
    
    path('<slug:slug>/<int:pk>/', views.CourseDetailView.as_view(), name="course_detail"),
    path('<slug:slug>/<int:pk>/edit/', views.CourseUpdateView.as_view(), name='course_update'),
    path('<slug:slug>/<int:pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),

    # urls for units
    path('<str:school>/<slug:slug>/',
         views.UnitsListView.as_view(), name='units_list'
         ),
    path('<str:school>/<slug:slug>/students/',
         views.StudentListView.as_view(), name='students'
         ),
    path('<str:school>/<slug:slug>/new/', views.UnitCreateView.as_view(), name='unit_create'),
    path('<str:school>/<slug:slug>/<int:pk>/', views.UnitDetailView.as_view(), name="unit_detail"),
    path('<str:school>/<slug:slug>/<int:pk>/edit/', views.UnitUpdateView.as_view(), name='unit_update'),
    path('<str:school>/<slug:slug>/<int:pk>/delete/', views.UnitDeleteView.as_view(), name='unit_delete'),


     #urls for lectures
    path('<str:school>/<str:course>/<slug:slug>/',
         views.LecturesListView.as_view(), name='lectures_list'
    ),
    path('<str:school>/<str:course>/<slug:slug>/new/', views.LectureCreateView.as_view(), name='lecture_create'),
     path('<str:school>/<str:course>/<str:unit>/<slug:slug>/',
         views.LectureDetailView.as_view(), name='lectures_detail'
         ),
    path('<str:school>/<str:course>/<slug:slug>/<int:pk>/edit/', views.LectureUpdateView.as_view(), name='lecture_update'),
    path('<str:school>/<str:course>/<slug:slug>/<int:pk>/delete/', views.LectureDeleteView.as_view(), name='lecture_delete'),
    


    path('<str:school>/<str:course>/<str:unit>/<slug:slug>/attendance/',
         views.AttendanceListView.as_view(), name='attendance_list'
         ),
    path('<str:school>/<str:course>/<slug:slug>/students',
         UnitRegisteredStudents.as_view(), name='unit_student_list'
         ),
    path('<str:school>/<str:course>/<slug:slug>/students/new',
         UnitRegistrationView.as_view(), name='unit_student_registration'
         ),
   

]

meru_class_attendance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),
    path('learning/', include('learningAttendance.urls')),
    path('registration/', include('registration.urls')),
    # path('attendance/', include('attendance.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from . import views
from learningAttendance.views import unit_list_pdf

app_name = 'registration'
urlpatterns = [
    path("registered_units", views.registered_units_view, name="registered_units"),
    path('profile/<int:pk>/delete/', views.RegistrationDeleteView.as_view(), name='registration_delete'),
   
    path('profile/<slug:slug>/unit_registration', views.available_units_for_registration, name='unit_registration'),
    path('unit_registration/<slug:slug>/register_unit/', views.registration, name='unit_registration_new'),
    path('courses_units/<int:pk>/units/', unit_list_pdf, name="unit_list_pdf"),

    path('attendance_request', views.AttendanceRequest.as_view(), name='attendance_request'),
    # path('mark_attendance', views.markAttendance, name='mark_attendance'),
    path('attendance/<slug:slug>', views.class_attendance, name='attendance'),


]

users/urls.py
from django.urls import path
from . import views
from learningAttendance.views import StudentListView


urlpatterns = [
    path('', views.login_request, name='login_request'),
    path('student_login/', views.student_login, name='student_login'),
    path('staff_login/', views.staff_login, name='staff_login'),
    path('logout/', views.user_logout, name='logout'),


    path('profile/', views.my_course_info, name="profile"),
    path('profile>/<slug:slug>/units',
         views.StudentUnitsList.as_view(), name='all_units'
         ),
    path("profile/registered_units/", views.registered_units_view, name="registered_units"),
    path('profile/registered_units/<slug:slug>/attendance/',
         views.student_attendance_report, name='student_attendance_report'
         ),
    path('profile/registered_units/<slug:slug>/',
         views.StudentLecturesList.as_view(), name='student_lectures'
         ),

    path('update_profile_pic', views.update_profile_pic, name="update_profile_pic"),



    path('lecturer/', views.lecturer_profile, name="lecturer_profile"),
    path('profile_update', views.update_lecturer_pic, name="update_lecturer_pic"),
    path('lecturer/units/', views.lecturer_units, name="lecturer_units"),
    path('lecturer/units/<slug:slug>/',
         views.LecturesListView.as_view(), name='lecturer_lectures'
         ),
    path('lecturer/units/<slug:slug>/attendance',
         views.LecturesAttendanceView.as_view(), name='lecturer_attendance'
         ),  
     path('lecturer/units_attendance/', views.lecturer_units_report, name="lecturer_units_report"),
     path('lecturer/<slug:slug>/units_attendance/', views.lecturer_lectures_report, name="lecturer_lectures_report"),
     path('lecturer/units/<slug:slug>/attendance_report',
         views.lecturer_student_attendance_report, name='lecture_attendance_report'
         ),
    path('lecturer/units/<str:unit>/<slug:slug>/',
         views.LectureDetailView.as_view(), name='lecture_detail'
         ),



    path('students/', views.UserListView.as_view(), name="users_list"),

    path('students/new/', views.UserCreateView.as_view(), name='user_new'),
    path('students/<slug:slug>/', views.UserDetailView.as_view(), name="user_detail"),
    path('students/<slug:slug>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('students/<slug:slug>/delete/', views.UserDeleteView.as_view(), name='user_delete'),
     path('students/units/<str:unit>/<slug:slug>/lectures/',
         views.StudentLectureDetailView.as_view(), name='student_lecture_detail'
         ),

]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django.forms import ModelForm
from django.http import HttpResponse


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = (
            'username', 'first_name', 'last_name', 'username', 'email',  'year', 'semester',
            'school',
            'course', 'is_staff',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = [
            'username', 'first_name', 'last_name', 'username', 'email', 'year', 'semester',
            'school',
            'course', 'is_staff', ]


class UserUpdateForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'username', 'email', 'profile_pic', 'year', 'semester',
                  'school',
                  'course', 'is_staff', ]


class UpdateProfilePic(forms.Form):
    image = forms.ImageField()

users/views.py
from os import path
from urllib.request import urlopen

from django import forms
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import CustomUser
from .forms import CustomUserCreationForm, UserUpdateForm, UpdateProfilePic
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from learningAttendance.models import Course, Unit, Lecture
from registration.models import Registration, Attendance


def login_request(request):
    return render(request, "registration/login.html")


def staff_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_superuser:
                login(request, user)
                return HttpResponseRedirect(reverse('meru_learning:schools_list'))
            elif user.is_staff:
                login(request, user)
                return HttpResponseRedirect(reverse('lecturer_profile'))
            elif user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('student_login'))
                # return HttpResponse('Please Go back to Login and select Student Login')  # student_panel
            else:
                return HttpResponse("ACCOUNT IS DEACTIVATED")
        else:
            return HttpResponse("Your username or password is wrong <br> <a href="">click here to try again</a>")
    else:
        return render(request, 'registration/staff_login.html')


def student_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_superuser:
                login(request, user)
                return HttpResponseRedirect(reverse('staff_login'))
            elif user.is_staff:
                login(request, user)
                return HttpResponseRedirect(reverse('staff_login'))
            elif user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('profile'))  # student_panel
            else:
                return HttpResponse("ACCOUNT IS DEACTIVATED")
        else:
            return HttpResponse("Your username or password is wrong <br> <a href="">click here to try again</a>")
    else:
        return render(request, 'registration/student_login.html')

# @login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))


def my_course_info(request):
    courses_list = []
    courses = Course.objects.filter(course_name=request.user.course)
    for my_course in courses:
        courses_list.append(my_course)
    registered_units = Registration.objects.filter(user=request.user)

    if 'profile_pic' in request.POST:
        form = UpdateProfilePic(request.POST, request.FILES)
        if form.is_valid():
            m = CustomUser.objects.get(username=request.user.username)
            m.profile_pic = form.cleaned_data['image']
            m.save()
        return redirect('profile')

    context = {
        "courses": courses_list,
        "registered_units": registered_units

    }
    return render(request, "profile.html", context)


@login_required
def lecturer_profile(request):
    unit = Unit.objects.filter(lecturer=request.user)
    if 'profile_pic' in request.POST:
        form = UpdateProfilePic(request.POST, request.FILES)
        if form.is_valid():
            m = CustomUser.objects.get(username=request.user.username)
            m.profile_pic = form.cleaned_data['image']
            m.save()
        return redirect('lecturer_profile')
    context = {
        "units": unit,

    }
    return render(request, 'lecturer/lecturer_profile.html', context)


def lecturer_student_attendance_report(request, slug):
    lecture = get_object_or_404(Lecture, slug=slug)
    attendance_list = Attendance.objects.filter(lecture=lecture)

    context = {
        "attendance_list": attendance_list,
    }
    return render(request, "lecturer/lecturer_student_attendance_report.html", context)



def update_lecturer_pic(request):
    return render(request, "profile_updates/update_lecturer_pic.html")


class LecturesListView(DetailView):
    context_object_name = 'units'
    model = Unit
    template_name = "lecturer/lectures.html"


class LecturesAttendanceView(DetailView):
    context_object_name = 'units'
    model = Unit
    template_name = "lecturer/lectures_attendance.html"


class LectureDetailView(DetailView):
    context_object_name = 'lecture'
    model = Lecture
    template_name = "lecturer/lecture_detail.html"


def lecturer_units(request):
    unit = Unit.objects.filter(lecturer=request.user)
    context = {
        "units": unit,

    }
    return render(request, "lecturer/lecturer_units.html", context)

def lecturer_units_report(request):
    unit = Unit.objects.filter(lecturer=request.user)
    context = {
        "units": unit,

    }
    return render(request, "lecturer/lecturer_units_report.html", context)

def lecturer_lectures_report(request, slug):
    unit = get_object_or_404(Unit, slug=slug)
    lectures = Lecture.objects.filter(unit=unit)
    context = {
        "lectures": lectures,

    }
    return render(request, "lecturer/lecturer_lectures_report.html", context)


def update_profile_pic(request):
    return render(request, "profile_updates/update_profile_pic.html")


class StudentUnitsList(DetailView):
    context_object_name = 'courses'
    model = Course
    template_name = "student/all_units.html"


class UserListView(ListView):
    model = CustomUser
    template_name = 'updates/all_students.html'
    context_object_name = "users"


class UserCreateView(CreateView):
    model = CustomUser
    template_name = 'updates/user_new.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users_list')


#
# class UserUpdateView(UpdateView):
#     model = CustomUser
#     template_name = 'updates/user_edit.html'
#     fields = ['first_name', 'last_name', 'username', 'email', 'year', 'school', 'course', 'semester', 'profile_pic',]

class UserUpdateView(UpdateView, SuccessMessageMixin):
    model = CustomUser
    template_name = 'updates/user_edit.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('users_list')
    success_message = 'update success'


class UserDeleteView(DeleteView):
    model = CustomUser
    template_name = 'updates/user_delete.html'
    success_url = reverse_lazy('users_list')


class UserDetailView(DetailView):
    model = CustomUser
    template_name = 'updates/user_detail.html'


class StudentLecturesList(DetailView):
    context_object_name = 'units'
    model = Unit
    template_name = "student/lectures.html"


def student_attendance_report(request, slug):
    total_attendance=0
    percentage =0
    unit = get_object_or_404(Unit, slug=slug)
    all_lectures = Lecture.objects.filter(unit=unit)
    attendance_list = Attendance.objects.filter(user=request.user)
    registered_lectures = []
    attended_lectures = []

    for lec in all_lectures:
        registered_lectures.append(lec)
    for attendance in attendance_list:
        lecture = attendance.lecture
        attended_lectures.append(lecture)
    if len(registered_lectures) == 0:
        HttpResponse("Ther are currently no  lectures in this unit")
    else:
        total_attendance = f'you have attended {len(attendance_list)} of {len(registered_lectures)} lectures'
        percentage = (len(attendance_list) / len(registered_lectures)) * 100
    if percentage >= 70:
        exam_qualification = 'you meet the minimum class attendance requirement to sit for exams'
    else:
        exam_qualification = 'you don\'t meet the minimum class attendance requirement to sit for exams'

    context = {
        "unit": unit,
        'exam_qualification': exam_qualification,
        "total_attendance": total_attendance,
        "lectures": attendance_list,
        "all_lectures": registered_lectures,
    }
    return render(request, "student/lectures_attendance_report.html", context)


def registered_units_view(request):
    registered_units = Registration.objects.filter(user=request.user)
    return render(request, 'student/units.html',
                  {"units": registered_units, })

class StudentLectureDetailView(DetailView):
    context_object_name = 'lecture'
    model = Lecture
    template_name = "student/lecture_detail.html"

users/templates/lecturer/lecture_detail.html
{% extends 'lecturer_panel.html' %}

{% block content %}


<div class="container-fluid video4" id="video4-c">
  <div class="title-wrapper mb-5">
    <div style="padding: 20px;">
      <p>

      </p>
    </div>
      <h4 class="mbr-section-title mbr-fonts-style mb-0 display-2">
          <strong>{{lecture.unit}}</strong></h4>
  </div>
    <div class="row d-flex  mb-3">
      <div class="col-8 col-lg-7 video-block" >
        {% if lecture.video %}
        <div class="row d-flex  mb-4" style="width:600; height:200;">
             <video controls   id="player-overlay">
                 <source src="{{lecture.video.url}}"  type="video/mp4">
               </video>
              
        
       </div>
      
  
       
        {%else%}
        <p class="mbr-description pt-2 mbr-fonts-style display-4">
          Video For this Lecture Not Available</p>
        {%endif%}  
        
      </div>
      <div class="col-12 col-lg">
          <div class="text-wrapper">
            <div style="background-color: rgb(67, 174, 201); padding: 10px;">
              <h5 class="mbr-section-subtitle mbr-fonts-style mb-3 display-5">
                  <strong>{{lecture.lecture_name}}</strong></h5>
              <p class="mbr-text mbr-fonts-style display-2">
                  <h2>Lecturer:</h2> <em>{{lecture.created_by.first_name}} {{lecture.created_by.last_name}}</em></p>
                  <p class="mbr-text mbr-fonts-style display-2">
                    <h2> Date Added:</h2> <em>{{lecture.created_at}}</em></p>
            </div><hr>
              
                    <div style=" padding: 10px; background-color: rgb(54, 174, 196); color: rgb(253, 253, 253); font-size: large;">
                      <h2 class="card-title text-white"><strong>Download Power Point Presentation</strong></h2>
                      {% if lecture.ppt %}
                      <a href="{{lecture.ppt.url}}" download>
                      <button type="button" class="btn btn-black"><h2><span class="text-white">Get ppt</span></h2></button>
                      </a>
                      {% else %}
                      <p class="card-text" > No PPT available</p>
                      {% endif %}</div><hr>

                      <div style="  padding: 10px; background-color: rgb(54, 174, 196); color: rgb(253, 253, 253); font-size: large;">
                        <h2 class="card-title text-white"><strong>Download Notes</strong></h2>
                        {% if lecture.notes %}
                        <a href="{{lecture.notes.url}}" download>
                        <button type="button" class="btn btn-black"><h2><span class="text-white">Get Notes</span></h2></button>
                        </a>
                        {% else %}
                        <p class="card-text" > Notes Not available</p><hr>
                        {% endif %}</div>

                        <div style="  padding: 10px; background-color: rgb(54, 174, 196); color: rgb(253, 253, 253); font-size: large;">
                          <h2 class="card-title text-white"><strong>Download Video</strong></h2>
                          {% if lecture.ppt %}
                          <a href="{{lecture.video.url}}" download>
                          <button type="button" class="btn btn-black"><h2><span class="text-white">Get Video</span></h2></button>
                          </a>
                          {% else %}
                          <p class="card-text" >Video Not available</p>
                          {% endif %}</div><hr>
                          
          </div>
          <div class="row d-flex  mb-3">
      
            <a class="btn btn-secondary display-4" href="{% url 'meru_learning:lecture_delete' slug=lecture.unit.slug course=lecture.unit.course.slug school=lecture.unit.course.school.slug pk=lecture.pk %}">Delete&nbsp;</a>
            <a class="btn btn-black display-4" href="{% url 'meru_learning:lecture_update' slug=lecture.unit.slug course=lecture.unit.course.slug school=lecture.unit.course.school.slug pk=lecture.pk %}">Update</a>
            
          
     
    </div>
      </div>
      <div style="padding: 280px;">
        <p>

        </p>
      </div>
  </div>


{% endblock %}

users/templates/lecturer/lecturer_lectures_report.html
{% extends 'lecturer_panel.html' %}

{% block content %}
<style>
    .card-text{
        color: rgb(255, 255, 255);
        padding-left: 20px;
    }
    .card-text-btn{
        font-size: 2.2rem;
        padding: 0.5rem;
        background-color: rgb(182, 211, 186);
        box-shadow: 5px 10px 30px rgba(18, 156, 13, 0.2);
        border-radius: 20px;
        color: #ffffff;
        cursor: pointer;
        text-align: center;

    }
    .category-name-cap{
        border-radius: 20px;
        text-align: center;
    }
    .see-more-btn{
        width: 190px;
        height: 44px;
        display: flex;
        justify-content: center;
        align-items: center;
        color: white;
        background-color: #07221d;
        border-radius: 20px;
        box-shadow: 15px 20px 40px rgba(172, 128, 9, 0.2);
        font-size: 28px;
        text-decoration: none;
        margin-left: 40px;

}
</style>

  <div class="container-fluid">
    <div style="padding: 40px;">
        <p></p>
    </div>
    <div class="alert alert-success text-center " role="alert">
        <h1>Select the lecture to View Attendance</h1>
    </div>
    <div class="row mt-4"> {% for lecture in lectures %}
        <div class="item features-image сol-12 col-md-6 col-lg-4">
            
            <div class="item-wrapper">
               
                <div class="item-content">
                    <h5 class="item-title mbr-fonts-style display-3"><strong> {{lecture.lecture_name}}</strong></h5>
                    <h5 class="item-title mbr-fonts-style display-7"><strong> Unit: {{lecture.unit}}</strong></h5>
                    <p class="item-title mbr-fonts-style display-7"><strong>Lecturer: {{lecture.created_by}}</strong></p>
                </div>
                <div class="mbr-section-btn item-footer mt-2">
                 
                  <a href="{% url 'lecture_attendance_report' slug=lecture.slug  %}" class="btn item-btn btn-secondary display-7" target="">Select >></a>
                </div>
            </div>
            
        </div>
        {% endfor%}
    </div>
   
    <div style="padding: 30px;">
        <p></p>
    </div>
  </div>

{% endblock content %}

users/templates/lecturer/lecturer_profile.html
{% extends 'lecturer_panel.html'%}

{%block content%}

<style>
    .user-image img{
        border-radius: 50%;
    }
</style>
<div class="container-fluid">
  <div style="padding: 1px;">
      <p></p>
  </div>
  {% if user.profile_pic %}
  <div class="user-image">
         <img src="{{user.profile_pic.url}}" alt="profile pic" height="200px" width="200px"><br>
     </div><p>
 
 
     {% else %}
 <p>visit admin to add your profile pic</p>
     {%endif%}
 
 <div class="row">
 <div class="col-12">
   <div class="card bg-light ms-6 me-6 mb-6 display-2">
     <div class="card-header">
       <i class="fa-solid fa-list"></i> Personal Information
     </div>
     <div class="card-body">
       <p class="card-text">
         <div class="table-responsive">
           <table class="table table-hover">
   <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Payroll Number</th>
      <th scope="col">Email</th>
    </tr>
   </thead>
   <tbody>
    <tr>
      <td>{{user.first_name}} </td>
      <td>{{user.last_name}}</td>
      <td>{{user.username}}</td>
      <td>{{user.email}}</td>
    </tr>
   </tbody>
 </table>
         </div>
       </p>
     </div>
     </div>
 
   </div>
 </div>
 <hr>
 <br>
 <div class="alert alert-success text-center " role="alert">
     <h1>Your Current Teaching Subjects </h1>
 </div>
 <div class="row">
 <div class="col-12">
   <div class="card bg-light ms-6 me-6 mb-6 display-2">
     <div class="card-body">
       <p class="card-text">
         <div class="table-responsive">
           <table class="table table-hover">
             <thead>
               <tr>
                 <th scope="col">Unit</th>
                 <th scope="col" >Course</th>
                 <th scope="col">On Offer</th>
                 <th scope="col">Semester</th>
                 <th scope="col">Actions</th>
               </tr>
             </thead>
             <tbody>
                 {% for unit in units %}
              <tr>
                 <td>
                     <h3>{{unit.unit_name}}</h3>
                 </td>
                 <td>{{unit.course}}</td>
                 <td>{{unit.is_offered}}</td>
                 <td>{{unit.semester}}</td>
                 <td>
                         <a class="btn btn-black" href="{% url 'lecturer_lectures' slug=unit.slug %}">
                          View Lectures
                         </a>
                      <a class="btn btn-black" href="{% url 'meru_learning:unit_student_list' slug=unit.slug course=unit.course.slug school=unit.course.school%}">
                           Registered Students
                         </a>
                 </td>
 
 
              </tr>
              {% endfor %}
             </tbody>
           </table>
         </div>
       </p>
     </div>
 </div>
 
 </div>
 </div>
  <div style="padding: 30px;">
      <p></p>
  </div>
</div>

  

{%endblock%}

users/templates/lecturer/lecturer_student_attendance_report.html
{% extends 'lecturer_panel.html'%}

{%block content%}
<div class="container-fluid">
  <div style="padding: 30px;">
    <div class="row">
      <div class="col-12">
        <div class="card bg-light ms-6 me-6 mb-6 display-2">
          <div class="card-header">
           Student's Attendance Report
          </div>
          <div class="card-body">
            <p class="card-text">
              <div class="table-responsive">
                <table class="table table-hover display-4">
                  <thead class="diplay-3">
                    <tr >
                      <th scope="col"><h2><strong>Student Name</strong></h2></th>
                      <th  scope="col"><h2><strong>Reg Number</strong></h2></th>
                      <th scope="col"><h2><strong>Course</strong></h2></th>
                      <th scope="col"><h2><strong>Year</strong></h2></th>
                      <th scope="col"><h2><strong>Semester</strong></h2></th>
                      <th  scope="col"><h2><strong>lecture</strong></h2></th>
                      <th  scope="col"><h2><strong>Date attended</strong></h2></th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for user in attendance_list %}
                       <tr>
                          <td>{{user.user.first_name}} {{user.user.last_name}}</td>
                          <td>{{user.user.username}}</td>
                          <td>{{user.user.course}}</td>
                          <td>{{user.user.year}}</td>
                          <td>{{user.user.semester}}</td>
                          <td>{{user.lecture}}</td>
                          <td>{{user.date}}</td>
                       </tr>
                   {% endfor %}
                  </tbody>
                </table>
              </div>
            </p>
          </div>
      </div>
      
       
      </div>
      </div>
      <div style="padding: 80px;">
          <p>



          </p>
      </div>
</div>


{%endblock%}

users/templates/lecturer/lectures_attendance.html
{% extends 'lecturer_panel.html' %}

{% block content %}
<style>
    .card-text{
        color: rgb(255, 255, 255);
        padding-left: 20px;
    }
    .card-text-btn{
        font-size: 2.2rem;
        padding: 0.5rem;
        background-color: rgb(182, 211, 186);
        box-shadow: 5px 10px 30px rgba(18, 156, 13, 0.2);
        border-radius: 20px;
        color: #ffffff;
        cursor: pointer;
        text-align: center;

    }
    .category-name-cap{
        border-radius: 20px;
        text-align: center;
    }
    .see-more-btn{
        width: 190px;
        height: 44px;
        display: flex;
        justify-content: center;
        align-items: center;
        color: white;
        background-color: #07221d;
        border-radius: 20px;
        box-shadow: 15px 20px 40px rgba(172, 128, 9, 0.2);
        font-size: 28px;
        text-decoration: none;
        margin-left: 40px;

}
</style>
<div class="container-fluid">
    <div style="padding: 1px;">
        <p></p>
    </div>
   
  
    <div style="padding: 30px;">
        <p></p>
    </div>
  </div>
<div class="alert alert-dark text-center " role="alert">
    <h1>Choose the Lecture to take Attendance </h1>
</div>

<ul class="row">
      {% for lecture in units.lectures.all %}
       <li class="col-auto " >
                <div class ="card  bg-white mb-3 sm-3" style="width: 339px;">
                <div class="card-body">
                    <h2 class="category-name-cap  "> {{lecture.lecture_name}}</h2><hr>
                    <h3 class="card-text btn ">{{lecture.unit}}</h3><hr>
                     <h3 class="card-text btn ">Lecturer: {{lecture.created_by}}</h3><hr>
                     <button class="btn btn-indigo btn-rounded btn-md">
                    <a href="{% url 'registration:attendance' slug=lecture.slug  %}">
                    <h2>
                        <span>Select</span>
                    </h2>
                    </a></button>

                </div>
            </div>
        </li>
    {% endfor %}
</ul>
{% endblock content %}